name: Submit Translation
description: Enter the Zolai source sentence in the title field

labels: [translation]

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Instructions
        🔤 **Enter the Zolai (source) sentence as the issue title above.**  
        💬 Then fill in the English translation and any notes below.

  - type: input
    id: target
    attributes:
      label: English (Target Text)
      placeholder: e.g. This is my house.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes or Explanation (optional)
      placeholder: Grammar, structure, alternate meanings...
    validations:
      required: false
