name: Submit Translation
description: Submit a new translation task
title: "[Translation] "
labels: [translation]
body:
  - type: input
    id: language
    attributes:
      label: Target Language
      placeholder: e.g. Zomi, Spanish, Hindi
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Source Text
      placeholder: Paste the source text here
    validations:
      required: true

  - type: textarea
    id: translation
    attributes:
      label: Translation
      placeholder: Enter your translation here
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: Grammar decisions, unclear meanings, etc.
