name: Submit Translation
description: Submit a new translation task
labels: [translation]
# title: "[Zolai]"
body:
  - type: markdown
    attributes:
      value: |
        ## Instructions
        **Enter the Zolai (Source Text) sentence as the issue title above.**  
        Then fill in the English translation and any notes below.
        **zo**: 💬 Hih ka inn hi -> **en**: 💬 This is my house.

  - type: input
    id: target
    attributes:
      label: English
      placeholder: e.g. This is my house.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: Grammar, structure, alternate meanings...
    validations:
      required: false
