name: Submit Translation
description: Submit a new translation task
title: "[Translation] "
labels: [translation]
body:
  - type: input
    id: source
    attributes:
      label: Source Language
      placeholder: Zolai
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target Text
      placeholder: English
    validations:
      required: true
