name: Submit Translation
description: Submit a new translation task
title: "[Translation] "
labels: [translation]
type: issue
body:
  - type: input
    id: source
    attributes:
      label: Zolai (Source Text)
      placeholder: Zolai
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: English (Target Text)
      placeholder: English
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes or Explanation (optional)
      placeholder: Grammar notes, ambiguity, or why you chose this phrase.
    validations:
      required: false