name: Submit Translation
description: Submit a new translation task
title: "{{ inputs.source }}"
labels: [translation]
body:
  - type: input
    id: source
    attributes:
      label: Zolai (Source Text)
      description: Enter the phrase or sentence to translate
      placeholder: e.g. Zolai text here
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: English (Target Text)
      description: Your best translation of the source
      placeholder: e.g. English translation
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes or Explanation (optional)
      placeholder: Grammar notes, ambiguity, or why you chose this phrase.
    validations:
      required: false
