name: Submit Translation
description: Submit a new translation task
title: "[Translation] "
labels: [translation]
body:
  - type: input
    id: source
    attributes:
      label: Zolai (Source Text)
      placeholder: Enter source sentence in Zolai
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: English (Target Text)
      placeholder: Enter translated sentence in English
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes or Explanation (Optional)
      description: Explain grammar, ambiguity, or context if needed
      placeholder: Grammar notes, ambiguity, reasoning, etc.
    validations:
      required: false