# ./config/data.yaml
# Configuration for data paths, sources, and indexing.

paths:
  # Root project directories
  root_dir: "."
  data_dir: "./data"
  config_dir: "./config"
  experiments_dir: "./experiments"
  tmp_dir: "./tmp"
  
  # Subdirectories within the data directory
  corpus_dir: "./data/corpus"
  template_dir: "./data/templates"
  shared_template_dir: "./data/templates/shared"

  # Index file for TSV datasets
  datasets_index_file: "./data/corpus/datasets.yaml"
