# ./config/data.yaml
# Configuration for data sources.
# Paths are inherited from default.yaml

defaults:
  - default

# Describes the data sources to be used.
# The data loader will look for an index.yaml in each source path.
sources:
  - name: "parallel_base"
    path: "${paths.parallel_base}"
  # - name: "templates"
  #   path: "${paths.templates}"

# Preprocessing settings applied to all loaded data.
preprocessing:
  lowercase: true
  normalize_punctuation: true # Separates punctuation like "word." -> "word ."
