# config/default.yaml
# This file serves as the base configuration.
# It defines global project paths and default settings that can be
# referenced or overridden by other specific configuration files.

# --- Project Paths ---
# Defines the root directories for major components of the project.
# Using placeholders like '${paths.root}/data' allows for easy relocation
# of the entire project.

paths:
  root: "."              # Project root directory.
  data: "${paths.root}/data"
  source_code: "${paths.root}/src"
  experiments: "${paths.root}/experiments"
  docs: "${paths.root}/docs"
  notebooks: "${paths.root}/notebooks"

# --- General Settings ---
# High-level settings for the project.

project_name: "ZoSia"
description: "Bidirectional NMT for Zolai (zo) and English (en)"

# Default language pair configuration. 'src' is source, 'tgt' is target.
# This can be overridden during training or inference.
lang:
  src: "en"
  tgt: "zo"
