# ./config/default.yaml
# General project settings and core paths.

project_name: "ZoSia"
description: "A Seq2Seq model for Zolai-English translation."
version: "0.1.0"

# Core project paths.
# These can be overridden by the .env file.
paths:
  root: "."
  data: "${paths.root}/data"
  source_code: "${paths.root}/zo"
  experiments: "${paths.root}/experiments"
  config: "${paths.root}/config"
  env_file: "${paths.root}/.env"

  # Specific data paths
  parallel_base: "${paths.data}/parallel_base"
  monolingual: "${paths.data}/monolingual"
  templates: "${paths.data}/templates"
  locale: "${paths.data}/locale"
