# ./config/model.yaml
# Default hyperparameters for the NMT model architecture and training.

# --- Training Settings ---
training:
  epochs: 150
  batch_size: 32
  learning_rate: 0.0001
  validation_split: 0.15
  patience: 10

# --- Model Architecture ---
architecture:
  embedding_size: 256
  num_heads: 4
  ff_hidden_size: 512
  num_layers: 3
  dropout: 0.1

# --- Tokenizer Settings ---
tokenizer:
  vocab_size: 8000
