# ./config/model.yaml
# Hyperparameters for the Seq2Seq model.

defaults:
  - default

# Can be 'cpu' or 'cuda'. 'auto' will detect automatically.
device: "auto"

# --- Model Architecture ---
# Set attention to true to use the more advanced attention-based decoder.
attention: true

encoder:
  hidden_size: 256
  # Other encoder params like num_layers can be added here.

decoder:
  hidden_size: 256
  # Other decoder params can be added here.
