# ./config/tokenizer.yaml
# Settings for the tokenizer and vocabulary.

defaults:
  - default

# Special tokens used by the model.
special_tokens:
  sos: "<SOS>"
  eos: "<EOS>"
  pad: "<PAD>"
  unk: "<UNK>" # For unknown words

# Dynamic calculation of max length based on the dataset.
# A fixed value can be set here to override it.
# max_length: 50
max_length: "auto"
