# ./config/training.yaml
# Hyperparameters related to the training process.

training:
  learning_rate: 0.0005
  batch_size: 32
  num_epochs: 10
  # Set to true to resume training from the last saved checkpoint
  resume: true
